export enum InventoryMovementType {
  INTAKE = 'INTAKE',
  PACKAGING = 'PACKAGING',
  WEBSITE_ORDER = 'WEBSITE_ORDER',
  SHOP_DELIVERY = 'SHOP_DELIVERY',
  STAFF_ALLOCATION = 'STAFF_ALLOCATION',
  WALK_IN_SALE = 'WALK_IN_SALE',
  RETURN = 'RETURN',
  DAMAGE = 'DAMAGE',
  ADJUSTMENT = 'ADJUSTMENT',
}
